name: Vue3 Template
on: [push]
jobs:
  linter:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 17.1.0
          cache: 'npm'
      - run: npm install
      - run: npm run lint
